"""Central public data contracts, grouped by domain."""

from rag_demo.models.document import BlockKind, Chunk, ParsedBlock, ParsedMarkdownDocument
from rag_demo.models.evaluation import (
    BenchmarkReport,
    EvaluationHit,
    EvaluationMethod,
    EvaluationMetrics,
    EvaluationQuery,
    MethodEvaluation,
    QueryMeasurement,
)
from rag_demo.models.ingestion import IngestResult
from rag_demo.models.operations import CorpusInfo, DatabaseStatus, DoctorCheck, DoctorReport
from rag_demo.models.retrieval import (
    BM25BuildResult,
    BM25IndexError,
    BM25SearchResponse,
    BM25SearchResult,
    DenseQueryPlan,
    DenseQueryResponse,
    DenseRetrievalResponse,
    DenseSearchMode,
    DenseSearchResult,
    FusedCandidate,
    HybridRecallResponse,
    ScoredCandidate,
    SearchCandidate,
    SearchCandidateCounts,
    SearchConfidence,
    SearchConfidenceStatus,
    SearchRequest,
    SearchResponse,
    SearchTimings,
)
from rag_demo.models.rewrite import (
    AliasRule,
    QueryRewriteExperiment,
    QueryRewriteResult,
    QuerySearchResponse,
    ResultRankChange,
    ResultRankingComparison,
)

__all__ = [
    "AliasRule",
    "BM25BuildResult",
    "BM25IndexError",
    "BM25SearchResponse",
    "BM25SearchResult",
    "BenchmarkReport",
    "BlockKind",
    "Chunk",
    "CorpusInfo",
    "DatabaseStatus",
    "DenseQueryPlan",
    "DenseQueryResponse",
    "DenseRetrievalResponse",
    "DenseSearchMode",
    "DenseSearchResult",
    "DoctorCheck",
    "DoctorReport",
    "EvaluationHit",
    "EvaluationMethod",
    "EvaluationMetrics",
    "EvaluationQuery",
    "FusedCandidate",
    "HybridRecallResponse",
    "IngestResult",
    "MethodEvaluation",
    "ParsedBlock",
    "ParsedMarkdownDocument",
    "QueryMeasurement",
    "QueryRewriteExperiment",
    "QueryRewriteResult",
    "QuerySearchResponse",
    "ResultRankChange",
    "ResultRankingComparison",
    "ScoredCandidate",
    "SearchCandidate",
    "SearchCandidateCounts",
    "SearchConfidence",
    "SearchConfidenceStatus",
    "SearchRequest",
    "SearchResponse",
    "SearchTimings",
]
